// docs/content/samples/viewer/getting-started/basic.vue.vue
<template>
  <PDFViewer
    :config="{ src: 'https://snippet.embedpdf.com/ebook.pdf' }"
    :style="{ height: '500px' }"
    @ready="onReady"
  />
</template>

<script setup lang="ts">
import { PDFViewer } from '@embedpdf/vue-pdf-viewer';

function onReady(registry: unknown) {
  console.log('PDF viewer ready!', registry);
}
</script>

// website/src/samples/viewer/getting-started/basic.react.tsx
import { PDFViewer } from '@embedpdf/react-pdf-viewer';

export default function App() {
  return (
    <PDFViewer
      config={{ src: 'https://snippet.embedpdf.com/ebook.pdf' }}
      style={{ height: '500px' }}
      onReady={(registry) => {
        console.log('PDF viewer ready!', registry);
      }}
    />
  );
}
