// packages/plugin-thumbnail/src/vue/components/thumbnail-img.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import { useThumbnailCapability, useThumbnailPlugin } from '../hooks';
import type { ThumbMeta } from '@embedpdf/plugin-thumbnail';
import { ignore, PdfErrorCode } from '@embedpdf/models';

interface ThumbImgProps {
  /**
   * The ID of the document that this thumbnail belongs to
   */
  documentId: string;
  meta: ThumbMeta;
}

const props = defineProps<ThumbImgProps>();

const { provides: thumbs } = useThumbnailCapability();
const { plugin: thumbnailPlugin } = useThumbnailPlugin();

const canvasRef = ref<HTMLCanvasElement | null>(null);
const hasContent = ref(false);
const refreshTick = ref(0);

// Watch for refresh events for this specific document
watch(
  [() => thumbnailPlugin.value, () => props.documentId, () => props.meta.pageIndex],
  ([plugin, docId, pageIdx], _, onCleanup) => {
    if (!plugin) return;

    const scope = plugin.provides().forDocument(docId);
    const unsubscribe = scope.onRefreshPages((pages) => {
      if (pages.includes(pageIdx)) {
        refreshTick.value++;
      }
    });

    onCleanup(unsubscribe);
  },
  { immediate: true },
);

function paintBitmap(bitmap: ImageBitmap) {
  if (!canvasRef.value) return;
  try {
    const canvas = canvasRef.value;
    canvas.width = bitmap.width;
    canvas.height = bitmap.height;
    canvas.getContext('2d')!.drawImage(bitmap, 0, 0);
    hasContent.value = true;
  } catch {
    // Bitmap was closed
  }
}

// Render thumbnail when dependencies change
watch(
  [() => thumbs.value, () => props.documentId, () => props.meta.pageIndex, refreshTick],
  ([capability, docId, pageIdx], _, onCleanup) => {
    if (!capability) {
      hasContent.value = false;
      return;
    }

    const scope = capability.forDocument(docId);
    const task = scope.renderThumb(pageIdx, window.devicePixelRatio);

    task.wait((bitmap) => {
      paintBitmap(bitmap);
      // Do NOT close bitmap — LRU cache owns lifecycle
    }, ignore);

    onCleanup(() => {
      task.abort({
        code: PdfErrorCode.Cancelled,
        message: 'canceled render task',
      });
    });
  },
  { immediate: true },
);
</script>

<template>
  <canvas ref="canvasRef" :style="{ visibility: hasContent ? 'visible' : 'hidden' }" v-bind="$attrs" />
</template>

// packages/plugin-thumbnail/src/shared/components/thumbnail-img.tsx
import { useEffect, useState, useRef, HTMLAttributes, CSSProperties } from '@framework';
import { ThumbMeta } from '@embedpdf/plugin-thumbnail';
import { ignore, PdfErrorCode } from '@embedpdf/models';
import { useThumbnailCapability, useThumbnailPlugin } from '../hooks';

type ThumbnailImgProps = Omit<HTMLAttributes<HTMLCanvasElement>, 'style'> & {
  /**
   * The ID of the document that this thumbnail belongs to
   */
  documentId: string;
  style?: CSSProperties;
  meta: ThumbMeta;
};

function paintBitmap(canvas: HTMLCanvasElement, bitmap: ImageBitmap) {
  try {
    canvas.width = bitmap.width;
    canvas.height = bitmap.height;
    canvas.getContext('2d')!.drawImage(bitmap, 0, 0);
  } catch {
    // Bitmap was closed (e.g. LRU eviction)
  }
}

export function ThumbImg({ documentId, meta, style, ...props }: ThumbnailImgProps) {
  const { provides: thumbs } = useThumbnailCapability();
  const { plugin: thumbnailPlugin } = useThumbnailPlugin();

  const [hasContent, setHasContent] = useState(false);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);

  const [refreshTick, setRefreshTick] = useState(0);

  useEffect(() => {
    if (!thumbnailPlugin) return;
    const scope = thumbnailPlugin.provides().forDocument(documentId);
    return scope.onRefreshPages((pages) => {
      if (pages.includes(meta.pageIndex)) {
        setRefreshTick((tick) => tick + 1);
      }
    });
  }, [thumbnailPlugin, documentId, meta.pageIndex]);

  // Bitmap render effect
  useEffect(() => {
    const scope = thumbs?.forDocument(documentId);
    const task = scope?.renderThumb(meta.pageIndex, window.devicePixelRatio);
    task?.wait((output) => {
      const canvas = canvasRef.current;
      if (canvas) {
        paintBitmap(canvas, output);
        setHasContent(true);
      }
    }, ignore);

    return () => {
      task?.abort({
        code: PdfErrorCode.Cancelled,
        message: 'canceled render task',
      });
    };
  }, [thumbs, documentId, meta.pageIndex, refreshTick]);

  // Do NOT close bitmap — LRU cache owns lifecycle

  return (
    <canvas
      ref={canvasRef}
      style={{ ...style, visibility: hasContent ? 'visible' : 'hidden' }}
      {...props}
    />
  );
}
