// packages/plugin-annotation/src/svelte/components/TextMarkup.svelte
<script lang="ts">
  import { blendModeToCss, PdfAnnotationSubtype, PdfBlendMode, type Quad, type Rect } from '@embedpdf/models';
  import type { AnnotationTool } from '@embedpdf/plugin-annotation';
  import { useSelectionCapability } from '@embedpdf/plugin-selection/svelte';

  import { useAnnotationCapability } from '../hooks';
  import Highlight from './text-markup/Highlight.svelte';
  import Squiggly from './text-markup/Squiggly.svelte';
  import Underline from './text-markup/Underline.svelte';
  import Strikeout from './text-markup/Strikeout.svelte';

  interface TextMarkupProps {
    documentId: string;
    pageIndex: number;
    scale: number;
  }

  let { documentId, pageIndex, scale }: TextMarkupProps = $props();

  const selectionCapability = useSelectionCapability();
  const annotationCapability = useAnnotationCapability();

  let rects = $state<Rect[]>([]);
  let quads = $state<Quad[]>([]);
  let boundingRect = $state<Rect | null>(null);
  let activeTool = $state<AnnotationTool | null>(null);

  // Get scoped APIs for this document
  const selectionProvides = $derived(
    selectionCapability.provides ? selectionCapability.provides.forDocument(documentId) : null,
  );
  const annotationProvides = $derived(
    annotationCapability.provides ? annotationCapability.provides.forDocument(documentId) : null,
  );

  // Subscribe to selection changes
  $effect(() => {
    if (!selectionProvides) return;

    const off = selectionProvides.onSelectionChange(() => {
      rects = selectionProvides.getHighlightRectsForPage(pageIndex);
      quads = selectionProvides.getHighlightQuadsForPage(pageIndex);
      boundingRect = selectionProvides.getBoundingRectForPage(pageIndex);
    });
    return off;
  });

  // Subscribe to active tool changes
  $effect(() => {
    if (!annotationProvides) return;

    // Initialize with current active tool
    activeTool = annotationProvides.getActiveTool();

    const off = annotationProvides.onActiveToolChange((tool) => {
      activeTool = tool;
    });
    return off;
  });

  const mixBlendMode = $derived(
    activeTool?.defaults?.blendMode
      ? blendModeToCss(activeTool.defaults.blendMode)
      : activeTool?.defaults?.type === PdfAnnotationSubtype.HIGHLIGHT
        ? blendModeToCss(PdfBlendMode.Multiply)
        : blendModeToCss(PdfBlendMode.Normal),
  );
</script>

{#if boundingRect && activeTool && activeTool.defaults}
  {#if activeTool.defaults.type === PdfAnnotationSubtype.UNDERLINE}
    <div
      style:mix-blend-mode={mixBlendMode}
      style:pointer-events="none"
      style:position="absolute"
      style:inset="0"
    >
      <Underline
        strokeColor={activeTool.defaults?.strokeColor}
        opacity={activeTool.defaults?.opacity}
        segmentRects={rects}
        segmentQuads={quads}
        {scale}
      />
    </div>
  {:else if activeTool.defaults.type === PdfAnnotationSubtype.HIGHLIGHT}
    <div
      style:mix-blend-mode={mixBlendMode}
      style:pointer-events="none"
      style:position="absolute"
      style:inset="0"
    >
      <Highlight
        strokeColor={activeTool.defaults?.strokeColor}
        opacity={activeTool.defaults?.opacity}
        segmentRects={rects}
        segmentQuads={quads}
        {scale}
      />
    </div>
  {:else if activeTool.defaults.type === PdfAnnotationSubtype.STRIKEOUT}
    <div
      style:mix-blend-mode={mixBlendMode}
      style:pointer-events="none"
      style:position="absolute"
      style:inset="0"
    >
      <Strikeout
        strokeColor={activeTool.defaults?.strokeColor}
        opacity={activeTool.defaults?.opacity}
        segmentRects={rects}
        segmentQuads={quads}
        {scale}
      />
    </div>
  {:else if activeTool.defaults.type === PdfAnnotationSubtype.SQUIGGLY}
    <div
      style:mix-blend-mode={mixBlendMode}
      style:pointer-events="none"
      style:position="absolute"
      style:inset="0"
    >
      <Squiggly
        strokeColor={activeTool.defaults?.strokeColor}
        opacity={activeTool.defaults?.opacity}
        segmentRects={rects}
        segmentQuads={quads}
        {scale}
      />
    </div>
  {/if}
{/if}

// packages/plugin-annotation/src/vue/components/text-markup.vue
<template>
  <div
    v-if="boundingRect && activeTool"
    :style="{
      mixBlendMode: blendMode,
      pointerEvents: 'none',
      position: 'absolute',
      inset: 0,
    }"
  >
    <Highlight
      v-if="activeTool.defaults.type === PdfAnnotationSubtype.HIGHLIGHT"
      :strokeColor="activeTool.defaults.strokeColor"
      :opacity="activeTool.defaults.opacity"
      :segmentRects="rects"
      :segmentQuads="quads"
      :scale="scale"
    />
    <Underline
      v-else-if="activeTool.defaults.type === PdfAnnotationSubtype.UNDERLINE"
      :strokeColor="activeTool.defaults.strokeColor"
      :opacity="activeTool.defaults.opacity"
      :segmentRects="rects"
      :segmentQuads="quads"
      :scale="scale"
    />
    <Strikeout
      v-else-if="activeTool.defaults.type === PdfAnnotationSubtype.STRIKEOUT"
      :strokeColor="activeTool.defaults.strokeColor"
      :opacity="activeTool.defaults.opacity"
      :segmentRects="rects"
      :segmentQuads="quads"
      :scale="scale"
    />
    <Squiggly
      v-else-if="activeTool.defaults.type === PdfAnnotationSubtype.SQUIGGLY"
      :strokeColor="activeTool.defaults.strokeColor"
      :opacity="activeTool.defaults.opacity"
      :segmentRects="rects"
      :segmentQuads="quads"
      :scale="scale"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, onUnmounted, watchEffect, computed } from 'vue';
import { blendModeToCss, PdfAnnotationSubtype, PdfBlendMode, Quad, Rect } from '@embedpdf/models';
import { AnnotationTool } from '@embedpdf/plugin-annotation';
import { useSelectionCapability } from '@embedpdf/plugin-selection/vue';
import { useAnnotationCapability } from '../hooks';
import Highlight from './text-markup/highlight.vue';
import Underline from './text-markup/underline.vue';
import Strikeout from './text-markup/strikeout.vue';
import Squiggly from './text-markup/squiggly.vue';

const props = defineProps<{
  documentId: string;
  pageIndex: number;
  scale: number;
}>();

const { provides: selectionProvides } = useSelectionCapability();
const { provides: annotationProvides } = useAnnotationCapability();
const rects = ref<Rect[]>([]);
const quads = ref<Quad[]>([]);
const boundingRect = ref<Rect | null>(null);
const activeTool = ref<AnnotationTool | null>(null);

watchEffect((onCleanup) => {
  const unsubscribers: (() => void)[] = [];

  if (selectionProvides.value) {
    const scoped = selectionProvides.value.forDocument(props.documentId);
    const off = scoped.onSelectionChange(() => {
      rects.value = scoped.getHighlightRectsForPage(props.pageIndex);
      quads.value = scoped.getHighlightQuadsForPage(props.pageIndex);
      boundingRect.value = scoped.getBoundingRectForPage(props.pageIndex);
    });
    unsubscribers.push(off);
  }

  if (annotationProvides.value) {
    const scoped = annotationProvides.value.forDocument(props.documentId);
    // Initialize with current active tool
    activeTool.value = scoped.getActiveTool();

    const off = scoped.onActiveToolChange((event) => (activeTool.value = event));
    unsubscribers.push(off);
  }

  onCleanup(() => {
    unsubscribers.forEach((unsub) => unsub());
  });
});

const blendMode = computed(() => {
  if (!activeTool.value) return blendModeToCss(PdfBlendMode.Normal);
  const defaultMode =
    activeTool.value.defaults.type === PdfAnnotationSubtype.HIGHLIGHT
      ? PdfBlendMode.Multiply
      : PdfBlendMode.Normal;
  return blendModeToCss(activeTool.value.defaults.blendMode ?? defaultMode);
});
</script>
