// packages/plugin-render/src/vue/components/render-layer.vue
<script setup lang="ts">
import { ref, computed, watch, onBeforeUnmount } from 'vue';
import { ignore, PdfErrorCode, Rotation } from '@embedpdf/models';
import { useDocumentState } from '@embedpdf/core/vue';
import { useRenderCapability } from '../hooks';

interface RenderLayerProps {
  /**
   * The ID of the document to render from
   */
  documentId: string;
  /**
   * The page index to render (0-based)
   */
  pageIndex: number;
  /**
   * Optional scale override. If not provided, uses document's current scale.
   */
  scale?: number;
  /**
   * Optional device pixel ratio override. If not provided, uses window.devicePixelRatio.
   */
  dpr?: number;
  /**
   * Optional rotation override. If not provided, uses page rotation plus document rotation.
   */
  rotation?: Rotation;
}

const props = defineProps<RenderLayerProps>();

const { provides: renderProvides } = useRenderCapability();
const documentState = useDocumentState(() => props.documentId);

const canvasRef = ref<HTMLCanvasElement | null>(null);
let currentBitmap: ImageBitmap | null = null;

// Get refresh version from core state
const refreshVersion = computed(() => {
  if (!documentState.value) return 0;
  return documentState.value.pageRefreshVersions[props.pageIndex] || 0;
});

// Determine actual render options: use overrides if provided, otherwise fall back to document state
const actualScale = computed(() => {
  if (props.scale !== undefined) return props.scale;
  return documentState.value?.scale ?? 1;
});

const actualDpr = computed(() => {
  if (props.dpr !== undefined) return props.dpr;
  return window.devicePixelRatio;
});

const actualRotation = computed(() => {
  if (props.rotation !== undefined) return props.rotation;
  const pageRotation =
    documentState.value?.document?.pages.find((page) => page.index === props.pageIndex)?.rotation ??
    Rotation.Degree0;
  const documentRotation = documentState.value?.rotation ?? Rotation.Degree0;
  return ((pageRotation + documentRotation) % 4) as Rotation;
});

function paintBitmap(bitmap: ImageBitmap) {
  if (!canvasRef.value) return;
  try {
    const canvas = canvasRef.value;
    canvas.width = bitmap.width;
    canvas.height = bitmap.height;
    canvas.getContext('bitmaprenderer')!.transferFromImageBitmap(bitmap);
  } catch {
    // Bitmap was detached
  }
}

// Render page when dependencies change
watch(
  [
    () => props.documentId,
    () => props.pageIndex,
    actualRotation,
    actualScale,
    actualDpr,
    renderProvides,
    refreshVersion,
  ],
  ([docId, pageIdx, rotation, scale, dpr, capability], [prevDocId], onCleanup) => {
    if (!capability) {
      if (canvasRef.value) {
        const canvas = canvasRef.value;
        canvas.width = canvas.width; // clears the canvas
      }
      return;
    }

    // CRITICAL: Clear canvas immediately when documentId changes (not for zoom/scale)
    if (prevDocId !== undefined && prevDocId !== docId) {
      if (canvasRef.value) {
        const canvas = canvasRef.value;
        canvas.width = canvas.width; // clears the canvas
      }
    }

    const task = capability.forDocument(docId).renderPageBitmap({
      pageIndex: pageIdx,
      options: {
        scaleFactor: scale,
        dpr,
        rotation,
      },
    });

    task.wait((bitmap) => {
      if (currentBitmap) {
        currentBitmap.close();
      }
      currentBitmap = bitmap;
      paintBitmap(bitmap);
      currentBitmap = null; // transferred to canvas, don't close
    }, ignore);

    onCleanup(() => {
      task.abort({
        code: PdfErrorCode.Cancelled,
        message: 'canceled render task',
      });
      if (currentBitmap) {
        currentBitmap.close();
        currentBitmap = null;
      }
    });
  },
  { immediate: true },
);

onBeforeUnmount(() => {
  if (currentBitmap) {
    currentBitmap.close();
    currentBitmap = null;
  }
});
</script>

<template>
  <canvas
    ref="canvasRef"
    :style="{ width: '100%', height: '100%' }"
    v-bind="$attrs"
  />
</template>

// packages/plugin-render/src/shared/components/render-layer.tsx
import { useEffect, useRef, useMemo } from '@framework';
import type { CSSProperties, HTMLAttributes } from '@framework';

import { ignore, PdfErrorCode } from '@embedpdf/models';

import { useRenderCapability } from '../hooks/use-render';
import { useDocumentState } from '@embedpdf/core/@framework';

type RenderLayerProps = Omit<HTMLAttributes<HTMLCanvasElement>, 'style'> & {
  /**
   * The ID of the document to render from
   */
  documentId: string;
  /**
   * The page index to render (0-based)
   */
  pageIndex: number;
  /**
   * Optional scale override. If not provided, uses document's current scale.
   */
  scale?: number;
  /**
   * Optional device pixel ratio override. If not provided, uses the browser device pixel ratio.
   */
  dpr?: number;
  /**
   * Optional rotation override. If not provided, uses page rotation plus document rotation.
   */
  rotation?: Rotation;
  /**
   * Additional styles for the canvas element
   */
  style?: CSSProperties;
};

function paintBitmap(canvas: HTMLCanvasElement, bitmap: ImageBitmap) {
  try {
    canvas.width = bitmap.width;
    canvas.height = bitmap.height;
    canvas.getContext('bitmaprenderer')!.transferFromImageBitmap(bitmap);
  } catch {
    // Bitmap was detached
  }
}

/**
 * RenderLayer Component
 *
 * Renders a PDF page with smart prop handling:
 * - If scale/dpr/rotation props are provided, they override document state
 * - If not provided, component uses document's current state values
 * - Automatically re-renders when:
 *   1. Document state changes (scale, rotation)
 *   2. Page is refreshed (via REFRESH_PAGES action in core)
 */
export function RenderLayer({
  documentId,
  pageIndex,
  scale: scaleOverride,
  dpr: dprOverride,
  rotation: rotationOverride,
  style,
  ...props
}: RenderLayerProps) {
  const { provides: renderProvides } = useRenderCapability();
  const documentState = useDocumentState(documentId);

  const canvasRef = useRef<HTMLCanvasElement | null>(null);

  // Get refresh version from core state
  const refreshVersion = useMemo(() => {
    if (!documentState) return 0;
    return documentState.pageRefreshVersions[pageIndex] || 0;
  }, [documentState, pageIndex]);

  // Determine actual render options: use overrides if provided, otherwise fall back to document state
  const actualScale = useMemo(() => {
    if (scaleOverride !== undefined) return scaleOverride;
    return documentState?.scale ?? 1;
  }, [scaleOverride, documentState?.scale]);

  const actualDpr = useMemo(() => {
    if (dprOverride !== undefined) return dprOverride;
    return globalThis.devicePixelRatio ?? 1;
  }, [dprOverride]);

  const actualRotation = useMemo(() => {
    if (rotationOverride !== undefined) return rotationOverride;
    const pageRotation =
      documentState?.document?.pages.find((page) => page.index === pageIndex)?.rotation ??
      Rotation.Degree0;
    const documentRotation = documentState?.rotation ?? Rotation.Degree0;
    return ((pageRotation + documentRotation) % 4) as Rotation;
  }, [rotationOverride, documentState?.document, documentState?.rotation, pageIndex]);

  useEffect(() => {
    if (!renderProvides) return;

    let currentBitmap: ImageBitmap | null = null;
    const task = renderProvides.forDocument(documentId).renderPageBitmap({
      pageIndex,
      options: {
        scaleFactor: actualScale,
        dpr: actualDpr,
        rotation: actualRotation,
      },
    });

    task.wait((output) => {
      currentBitmap = output;
      const canvas = canvasRef.current;
      if (canvas) {
        paintBitmap(canvas, output);
        currentBitmap = null; // transferred to canvas
      }
    }, ignore);

    return () => {
      task.abort({
        code: PdfErrorCode.Cancelled,
        message: 'canceled render task',
      });
      if (currentBitmap) {
        currentBitmap.close();
        currentBitmap = null;
      }
    };
  }, [
    documentId,
    pageIndex,
    actualScale,
    actualDpr,
    actualRotation,
    renderProvides,
    refreshVersion,
  ]);

  const elementStyle: CSSProperties = {
    width: '100%',
    height: '100%',
    ...(style || {}),
  };

  return <canvas ref={canvasRef} {...props} style={elementStyle} />;
}
