// packages/plugin-annotation/src/shared/components/text-markup/highlight.tsx
import { CSSProperties, MouseEvent } from '@framework';
import { Quad, Rect } from '@embedpdf/models';

import { quadBoundsRelativeToContainer, quadClipPath, resolveTextMarkupSegments } from './quad-geometry';

type HighlightProps = {
  /** Stroke/markup color */
  strokeColor?: string;
  opacity?: number;
  segmentRects: Rect[];
  segmentQuads?: Quad[];
  rect?: Rect;
  scale: number;
  onClick?: (e: MouseEvent<HTMLDivElement>) => void;
  style?: CSSProperties;
  /** When true, AP image provides the visual; only render hit area */
  appearanceActive?: boolean;
};

export function Highlight({
  strokeColor,
  opacity = 0.5,
  segmentRects,
  segmentQuads,
  rect,
  scale,
  onClick,
  style,
  appearanceActive = false,
}: HighlightProps) {
  const resolvedColor = strokeColor ?? '#FFFF00';
  const segments = resolveTextMarkupSegments(segmentRects, segmentQuads);

  return (
    <>
      {segments.map((segment, i) => {
        const bounds = quadBoundsRelativeToContainer(segment, rect, scale);
        return (
          <div
            key={i}
            onPointerDown={onClick}
            style={{
              position: 'absolute',
              left: bounds.left,
              top: bounds.top,
              width: bounds.width,
              height: bounds.height,
              background: appearanceActive ? 'transparent' : resolvedColor,
              opacity: appearanceActive ? undefined : opacity,
              clipPath: appearanceActive ? undefined : quadClipPath(segment, rect, scale),
              pointerEvents: onClick ? 'auto' : 'none',
              cursor: onClick ? 'pointer' : 'default',
              zIndex: onClick ? 1 : undefined,
              ...style,
            }}
          />
        );
      })}
    </>
  );
}

// packages/plugin-annotation/src/vue/components/text-markup/highlight.vue
<template>
  <div
    v-for="(segment, i) in segments"
    :key="i"
    @pointerdown="onClick"
    :style="{
      position: 'absolute',
      left: `${quadBoundsRelativeToContainer(segment, rect, scale).left}px`,
      top: `${quadBoundsRelativeToContainer(segment, rect, scale).top}px`,
      width: `${quadBoundsRelativeToContainer(segment, rect, scale).width}px`,
      height: `${quadBoundsRelativeToContainer(segment, rect, scale).height}px`,
      background: appearanceActive ? 'transparent' : resolvedColor,
      opacity: appearanceActive ? undefined : opacity,
      clipPath: appearanceActive ? undefined : quadClipPath(segment, rect, scale),
      pointerEvents: onClick ? 'auto' : 'none',
      cursor: onClick ? 'pointer' : 'default',
      zIndex: onClick ? 1 : undefined,
    }"
  ></div>
</template>

<script lang="ts">
export default { inheritAttrs: false };
</script>

<script setup lang="ts">
import { computed } from 'vue';
import { Quad, Rect } from '@embedpdf/models';
import {
  quadBoundsRelativeToContainer,
  quadClipPath,
  resolveTextMarkupSegments,
} from '../../../shared/components/text-markup/quad-geometry';

const props = withDefaults(
  defineProps<{
    strokeColor?: string;
    opacity?: number;
    segmentRects: Rect[];
    segmentQuads?: Quad[];
    rect?: Rect;
    scale: number;
    onClick?: (e: PointerEvent) => void;
    appearanceActive?: boolean;
  }>(),
  {
    opacity: 0.5,
    appearanceActive: false,
  },
);

const resolvedColor = computed(() => props.strokeColor ?? '#FFFF00');
const segments = computed(() =>
  resolveTextMarkupSegments(props.segmentRects, props.segmentQuads),
);
</script>
