// packages/plugin-annotation/src/shared/components/text-markup/underline.tsx
import { CSSProperties, MouseEvent } from '@framework';
import { Quad, Rect } from '@embedpdf/models';

import {
  quadBoundsRelativeToContainer,
  resolveTextMarkupSegments,
  underlineSegmentPath,
} from './quad-geometry';

type UnderlineProps = {
  /** Stroke/markup color */
  strokeColor?: string;
  opacity?: number;
  segmentRects: Rect[];
  segmentQuads?: Quad[];
  rect?: Rect;
  scale: number;
  onClick?: (e: MouseEvent<HTMLDivElement>) => void;
  style?: CSSProperties;
  /** When true, AP image provides the visual; only render hit area */
  appearanceActive?: boolean;
};

export function Underline({
  strokeColor,
  opacity = 0.5,
  segmentRects,
  segmentQuads,
  rect,
  scale,
  onClick,
  style,
  appearanceActive = false,
}: UnderlineProps) {
  const resolvedColor = strokeColor ?? '#FFFF00';
  const thickness = 2 * scale;
  const segments = resolveTextMarkupSegments(segmentRects, segmentQuads);

  return (
    <>
      {segments.map((segment, i) => {
        const bounds = quadBoundsRelativeToContainer(segment, rect, scale);
        return (
          <div
            key={i}
            onPointerDown={onClick}
            style={{
              position: 'absolute',
              left: bounds.left,
              top: bounds.top,
              width: bounds.width,
              height: bounds.height,
              background: 'transparent',
              pointerEvents: onClick ? 'auto' : 'none',
              cursor: onClick ? 'pointer' : 'default',
              zIndex: onClick ? 1 : 0,
              ...style,
            }}
          >
            {!appearanceActive && (
              <svg
                style={{
                  position: 'absolute',
                  left: 0,
                  top: 0,
                  width: '100%',
                  height: '100%',
                  overflow: 'visible',
                  pointerEvents: 'none',
                }}
              >
                <path
                  d={underlineSegmentPath(segment, rect, scale)}
                  stroke={resolvedColor}
                  strokeWidth={thickness}
                  fill="none"
                  opacity={opacity}
                />
              </svg>
            )}
          </div>
        );
      })}
    </>
  );
}

// packages/plugin-annotation/src/vue/components/text-markup/underline.vue
<template>
  <div
    v-for="(segment, i) in segments"
    :key="i"
    @pointerdown="onClick"
    :style="{
      position: 'absolute',
      left: `${quadBoundsRelativeToContainer(segment, rect, scale).left}px`,
      top: `${quadBoundsRelativeToContainer(segment, rect, scale).top}px`,
      width: `${quadBoundsRelativeToContainer(segment, rect, scale).width}px`,
      height: `${quadBoundsRelativeToContainer(segment, rect, scale).height}px`,
      background: 'transparent',
      pointerEvents: onClick ? 'auto' : 'none',
      cursor: onClick ? 'pointer' : 'default',
      zIndex: onClick ? 1 : 0,
    }"
  >
    <svg
      v-if="!appearanceActive"
      :style="{
        position: 'absolute',
        left: 0,
        top: 0,
        width: '100%',
        height: '100%',
        overflow: 'visible',
        pointerEvents: 'none',
      }"
    >
      <path
        :d="underlineSegmentPath(segment, rect, scale)"
        :stroke="resolvedColor"
        :stroke-width="thickness"
        fill="none"
        :opacity="opacity"
      />
    </svg>
  </div>
</template>

<script lang="ts">
export default { inheritAttrs: false };
</script>

<script setup lang="ts">
import { computed } from 'vue';
import { Quad, Rect } from '@embedpdf/models';
import {
  quadBoundsRelativeToContainer,
  resolveTextMarkupSegments,
  underlineSegmentPath,
} from '../../../shared/components/text-markup/quad-geometry';

const props = withDefaults(
  defineProps<{
    strokeColor?: string;
    opacity?: number;
    segmentRects: Rect[];
    segmentQuads?: Quad[];
    rect?: Rect;
    scale: number;
    onClick?: (e: PointerEvent) => void;
    appearanceActive?: boolean;
  }>(),
  {
    opacity: 0.5,
    appearanceActive: false,
  },
);

const resolvedColor = computed(() => props.strokeColor ?? '#FFFF00');
const thickness = computed(() => 2 * props.scale);
const segments = computed(() =>
  resolveTextMarkupSegments(props.segmentRects, props.segmentQuads),
);
</script>
