// packages/plugin-render/src/svelte/components/RenderLayer.svelte
<script lang="ts">
  import type { HTMLCanvasAttributes } from 'svelte/elements';
  import { ignore, PdfErrorCode, Rotation } from '@embedpdf/models';
  import { useDocumentState } from '@embedpdf/core/svelte';
  import { useRenderCapability } from '../hooks';
  import { onDestroy } from 'svelte';

  interface RenderLayerProps extends Omit<HTMLCanvasAttributes, 'style'> {
    /**
     * The ID of the document to render from
     */
    documentId: string;
    /**
     * The page index to render (0-based)
     */
    pageIndex: number;
    /**
     * Optional scale override. If not provided, uses document's current scale.
     */
    scale?: number;
    /**
     * Optional device pixel ratio override. If not provided, uses window.devicePixelRatio.
     */
    dpr?: number;
    /**
     * Optional rotation override. If not provided, uses page rotation plus document rotation.
     */
    rotation?: Rotation;
    class?: string;
    style?: string;
  }

  // Single allowed $props() call
  const allProps: RenderLayerProps = $props();

  // Keep the rest reactive (Svelte will wire these to prop updates)
  let {
    documentId,
    scale: scaleOverride,
    dpr: dprOverride,
    rotation: rotationOverride,
    class: propsClass,
    style: propsStyle,
    pageIndex,
    ...attrs
  } = allProps;

  // Local non-reactive page index that only updates on actual change
  let localPageIndex = $state(pageIndex);

  // Watcher effect: only update localPageIndex if prop actually changes
  $effect(() => {
    if (pageIndex !== localPageIndex) {
      localPageIndex = pageIndex;
    }
  });

  const renderCapability = useRenderCapability();

  // Make document state follow the (reactive) documentId
  const documentState = useDocumentState(() => documentId);

  let canvasEl: HTMLCanvasElement | undefined = $state(undefined);
  let currentBitmap: ImageBitmap | null = null;

  // Track page refreshes from core
  const refreshVersion = $derived(documentState.current?.pageRefreshVersions?.[pageIndex] ?? 0);

  // Resolve actual scale / dpr (overrides win, otherwise follow document state)
  const actualScale = $derived(
    scaleOverride !== undefined ? scaleOverride : (documentState.current?.scale ?? 1),
  );

  const actualDpr = $derived(dprOverride !== undefined ? dprOverride : window.devicePixelRatio);

  const actualRotation = $derived.by(() => {
    if (rotationOverride !== undefined) return rotationOverride;
    const pageRotation =
      documentState.current?.document?.pages.find((page) => page.index === pageIndex)?.rotation ??
      Rotation.Degree0;
    const documentRotation = documentState.current?.rotation ?? Rotation.Degree0;
    return ((pageRotation + documentRotation) % 4) as Rotation;
  });

  function paintBitmap(bitmap: ImageBitmap) {
    if (!canvasEl) return;
    try {
      canvasEl.width = bitmap.width;
      canvasEl.height = bitmap.height;
      canvasEl.getContext('bitmaprenderer')!.transferFromImageBitmap(bitmap);
    } catch {
      // Bitmap was detached
    }
  }

  // Effect: reruns when:
  // - documentId changes
  // - actualScale changes
  // - actualDpr changes
  // - refreshVersion changes
  // - renderCapability.provides changes
  // It does NOT track pageIndex reactively.
  $effect(() => {
    const capability = renderCapability.provides;
    const docId = documentId;
    const scale = actualScale;
    const dpr = actualDpr;
    const rotation = actualRotation;
    const refresh = refreshVersion;
    const page = localPageIndex;

    if (!capability || !docId) {
      // Cleanup if no capability/doc
      if (canvasEl) {
        canvasEl.width = canvasEl.width; // clears the canvas
      }
      return;
    }

    const scoped = capability.forDocument(docId);

    const task = scoped.renderPageBitmap({
      pageIndex: page,
      options: {
        scaleFactor: scale,
        dpr,
        rotation,
      },
    });

    task.wait((bitmap) => {
      if (currentBitmap) {
        currentBitmap.close();
      }
      currentBitmap = bitmap;
      paintBitmap(bitmap);
      currentBitmap = null; // transferred to canvas, don't close
    }, ignore);

    return () => {
      task.abort({
        code: PdfErrorCode.Cancelled,
        message: 'canceled render task',
      });
      if (currentBitmap) {
        currentBitmap.close();
        currentBitmap = null;
      }
    };
  });

  onDestroy(() => {
    if (currentBitmap) {
      currentBitmap.close();
      currentBitmap = null;
    }
  });
</script>

<canvas
  bind:this={canvasEl}
  style={`width: 100%; height: 100%; ${propsStyle ?? ''}`}
  {...attrs}
  class={propsClass}
></canvas>

// packages/plugin-render/src/vue/components/render-layer.vue
<script setup lang="ts">
import { ref, computed, watch, onBeforeUnmount } from 'vue';
import { ignore, PdfErrorCode, Rotation } from '@embedpdf/models';
import { useDocumentState } from '@embedpdf/core/vue';
import { useRenderCapability } from '../hooks';

interface RenderLayerProps {
  /**
   * The ID of the document to render from
   */
  documentId: string;
  /**
   * The page index to render (0-based)
   */
  pageIndex: number;
  /**
   * Optional scale override. If not provided, uses document's current scale.
   */
  scale?: number;
  /**
   * Optional device pixel ratio override. If not provided, uses window.devicePixelRatio.
   */
  dpr?: number;
  /**
   * Optional rotation override. If not provided, uses page rotation plus document rotation.
   */
  rotation?: Rotation;
}

const props = defineProps<RenderLayerProps>();

const { provides: renderProvides } = useRenderCapability();
const documentState = useDocumentState(() => props.documentId);

const canvasRef = ref<HTMLCanvasElement | null>(null);
let currentBitmap: ImageBitmap | null = null;

// Get refresh version from core state
const refreshVersion = computed(() => {
  if (!documentState.value) return 0;
  return documentState.value.pageRefreshVersions[props.pageIndex] || 0;
});

// Determine actual render options: use overrides if provided, otherwise fall back to document state
const actualScale = computed(() => {
  if (props.scale !== undefined) return props.scale;
  return documentState.value?.scale ?? 1;
});

const actualDpr = computed(() => {
  if (props.dpr !== undefined) return props.dpr;
  return window.devicePixelRatio;
});

const actualRotation = computed(() => {
  if (props.rotation !== undefined) return props.rotation;
  const pageRotation =
    documentState.value?.document?.pages.find((page) => page.index === props.pageIndex)?.rotation ??
    Rotation.Degree0;
  const documentRotation = documentState.value?.rotation ?? Rotation.Degree0;
  return ((pageRotation + documentRotation) % 4) as Rotation;
});

function paintBitmap(bitmap: ImageBitmap) {
  if (!canvasRef.value) return;
  try {
    const canvas = canvasRef.value;
    canvas.width = bitmap.width;
    canvas.height = bitmap.height;
    canvas.getContext('bitmaprenderer')!.transferFromImageBitmap(bitmap);
  } catch {
    // Bitmap was detached
  }
}

// Render page when dependencies change
watch(
  [
    () => props.documentId,
    () => props.pageIndex,
    actualRotation,
    actualScale,
    actualDpr,
    renderProvides,
    refreshVersion,
  ],
  ([docId, pageIdx, rotation, scale, dpr, capability], [prevDocId], onCleanup) => {
    if (!capability) {
      if (canvasRef.value) {
        const canvas = canvasRef.value;
        canvas.width = canvas.width; // clears the canvas
      }
      return;
    }

    // CRITICAL: Clear canvas immediately when documentId changes (not for zoom/scale)
    if (prevDocId !== undefined && prevDocId !== docId) {
      if (canvasRef.value) {
        const canvas = canvasRef.value;
        canvas.width = canvas.width; // clears the canvas
      }
    }

    const task = capability.forDocument(docId).renderPageBitmap({
      pageIndex: pageIdx,
      options: {
        scaleFactor: scale,
        dpr,
        rotation,
      },
    });

    task.wait((bitmap) => {
      if (currentBitmap) {
        currentBitmap.close();
      }
      currentBitmap = bitmap;
      paintBitmap(bitmap);
      currentBitmap = null; // transferred to canvas, don't close
    }, ignore);

    onCleanup(() => {
      task.abort({
        code: PdfErrorCode.Cancelled,
        message: 'canceled render task',
      });
      if (currentBitmap) {
        currentBitmap.close();
        currentBitmap = null;
      }
    });
  },
  { immediate: true },
);

onBeforeUnmount(() => {
  if (currentBitmap) {
    currentBitmap.close();
    currentBitmap = null;
  }
});
</script>

<template>
  <canvas
    ref="canvasRef"
    :style="{ width: '100%', height: '100%' }"
    v-bind="$attrs"
  />
</template>
