// packages/plugin-annotation/src/vue/components/text-markup/highlight.vue
<template>
  <div
    v-for="(segment, i) in segments"
    :key="i"
    @pointerdown="onClick"
    :style="{
      position: 'absolute',
      left: `${quadBoundsRelativeToContainer(segment, rect, scale).left}px`,
      top: `${quadBoundsRelativeToContainer(segment, rect, scale).top}px`,
      width: `${quadBoundsRelativeToContainer(segment, rect, scale).width}px`,
      height: `${quadBoundsRelativeToContainer(segment, rect, scale).height}px`,
      background: appearanceActive ? 'transparent' : resolvedColor,
      opacity: appearanceActive ? undefined : opacity,
      clipPath: appearanceActive ? undefined : quadClipPath(segment, rect, scale),
      pointerEvents: onClick ? 'auto' : 'none',
      cursor: onClick ? 'pointer' : 'default',
      zIndex: onClick ? 1 : undefined,
    }"
  ></div>
</template>

<script lang="ts">
export default { inheritAttrs: false };
</script>

<script setup lang="ts">
import { computed } from 'vue';
import { Quad, Rect } from '@embedpdf/models';
import {
  quadBoundsRelativeToContainer,
  quadClipPath,
  resolveTextMarkupSegments,
} from '../../../shared/components/text-markup/quad-geometry';

const props = withDefaults(
  defineProps<{
    strokeColor?: string;
    opacity?: number;
    segmentRects: Rect[];
    segmentQuads?: Quad[];
    rect?: Rect;
    scale: number;
    onClick?: (e: PointerEvent) => void;
    appearanceActive?: boolean;
  }>(),
  {
    opacity: 0.5,
    appearanceActive: false,
  },
);

const resolvedColor = computed(() => props.strokeColor ?? '#FFFF00');
const segments = computed(() =>
  resolveTextMarkupSegments(props.segmentRects, props.segmentQuads),
);
</script>

// packages/plugin-annotation/src/svelte/components/text-markup/Highlight.svelte
<script lang="ts">
  import type { Quad, Rect } from '@embedpdf/models';
  import {
    quadBoundsRelativeToContainer,
    quadClipPath,
    resolveTextMarkupSegments,
  } from '../../../shared/components/text-markup/quad-geometry';

  interface HighlightProps {
    strokeColor?: string;
    opacity?: number;
    segmentRects: Rect[];
    segmentQuads?: Quad[];
    rect?: Rect;
    scale: number;
    onClick?: (e: MouseEvent) => void;
    style?: Record<string, string | number | undefined>;
    appearanceActive?: boolean;
  }

  let {
    strokeColor,
    opacity = 0.5,
    segmentRects,
    segmentQuads,
    rect,
    scale,
    onClick,
    style,
    appearanceActive = false,
  }: HighlightProps = $props();

  const resolvedColor = $derived(strokeColor ?? '#FFFF00');
  const segments = $derived(resolveTextMarkupSegments(segmentRects, segmentQuads));
</script>

{#each segments as segment, i (i)}
  {@const bounds = quadBoundsRelativeToContainer(segment, rect, scale)}
  <div
    role="button"
    tabindex={onClick ? 0 : -1}
    onpointerdown={onClick}
    style:position="absolute"
    style:left="{bounds.left}px"
    style:top="{bounds.top}px"
    style:width="{bounds.width}px"
    style:height="{bounds.height}px"
    style:background={appearanceActive ? 'transparent' : resolvedColor}
    style:opacity={appearanceActive ? undefined : opacity}
    style:clip-path={appearanceActive ? undefined : quadClipPath(segment, rect, scale)}
    style:pointer-events={onClick ? 'auto' : 'none'}
    style:cursor={onClick ? 'pointer' : 'default'}
    style:z-index={onClick ? 1 : undefined}
    {...style ? Object.fromEntries(Object.entries(style).map(([k, v]) => [`style:${k}`, v])) : {}}
  ></div>
{/each}
