// packages/framework/angular/stage/src/stage.ts
/**
 * `<epdf-stage>` — virtualizes and positions page surfaces by the camera, and
 * stamps each one with YOUR `<ng-template epdfPage>` — you bring the layers.
 *
 * NULL-SAFE BY DESIGN (a deliberate deviation from React's strict Stage):
 * Angular instantiates projected content eagerly, so a stage constructed
 * before any document exists must not crash — it renders zero pages and its
 * listeners no-op until the document arrives. Teach the document gate anyway:
 * document CHROME (toolbars, panels) still belongs behind `*epdfDocumentGate`.
 *
 * ZONE RULE: every DOM listener here attaches OUTSIDE Angular's zone — a
 * 120Hz pointermove stream must never trigger app-wide change detection.
 * State flows kernel → tick signal → computeds → bindings, so the adapter is
 * zone-agnostic (zoneless recommended, zone.js tolerated).
 */
import { isPlatformBrowser } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  contentChild,
  effect,
  ElementRef,
  inject,
  input,
  NgZone,
  PLATFORM_ID,
} from '@angular/core';
import { StageToken, createScrollHandler } from '@embedpdf/plugin-stage';
import type { StageCapability, VisiblePage } from '@embedpdf/plugin-stage';
import { InteractionToken } from '@embedpdf/plugin-interaction/contract';
import {
  injectDocumentId,
  injectKernelHost,
  injectOptionalCapability,
  injectOptionalCapabilityFor,
  injectOptionalSelectorFor,
  type CapabilityToken,
} from '@embedpdf/angular/runtime';
import type { PageFrame } from '@embedpdf/plugin-stage';
import { createStageSurface } from '@embedpdf/web';
import { EpdfPageChrome, EpdfPageTemplate } from './templates';
import { EpdfPageSurface } from './page-surface';

/** Which stage lens to bind to. Defaults to the main StageToken — pass a custom
 *  token to drive an additional lens (e.g. a wrapped thumbnail sidebar). */
export type StageTokenProp = CapabilityToken<StageCapability>;

const EMPTY_PAGES: VisiblePage[] = [];
const NO_FRAME: PageFrame = { top: 0, right: 0, bottom: 0, left: 0 };
const frameEqual = (a: PageFrame, b: PageFrame) =>
  a.top === b.top && a.right === b.right && a.bottom === b.bottom && a.left === b.left;

@Component({
  selector: 'epdf-stage',
  standalone: true,
  imports: [EpdfPageSurface],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    style: 'position: relative; overflow: hidden; touch-action: none; display: block;',
    '[style.cursor]': 'cursor()',
  },
  template: `
    @if (pageTemplate(); as tpl) {
      @for (p of pages(); track p.pon) {
        <epdf-page-surface
          [vp]="p"
          [frame]="frame()"
          [documentId]="documentId() ?? ''"
          [pageTpl]="tpl"
          [chromeTpl]="chromeTemplate()"
        />
      }
    }
    <!-- viewport-space overlay UI: anything projected into <epdf-stage>
         renders above the pages (menus, controls, scrollbars). -->
    <ng-content />
  `,
})
export class EpdfStage {
  /**
   * Route this Stage's pointer events to the interaction hub (page-resolved via
   * `pageAt`) — AND register this lens's tool-gated pan-scroll handler with it
   * (lens-scoped, so multiple stages on one document never pan each other).
   * Pan is then the `pan` tool's job and dragging in `pointer` mode selects
   * text (incl. across pages).
   *
   * Default TRUE: registering `interactionPlugin()` is the one opt-in — tools
   * just work; without the hub this is inert and the stage falls back to
   * built-in drag-to-pan, so a hub-less setup costs nothing. Set `false` on
   * SECONDARY lenses (a thumbnail rail) that should stay click-to-navigate
   * instead of feeding the document's tools.
   */
  readonly interaction = input(true);
  /**
   * With `interaction`: let drags over page GAPS pan regardless of the active
   * tool (and show a grab cursor there) — the gutter always pans; there is
   * nothing to draw/select outside a page. Default true.
   */
  readonly panFallback = input(true);
  /**
   * Ambient ZOOM gestures on this stage: ctrl/cmd+wheel and trackpad pinch
   * (Safari gesture events included). Default true. Turn OFF for follower
   * lenses with a fixed magnification (a thumbnail rail should scroll under
   * cmd+wheel, not zoom); pinches are still swallowed either way.
   */
  readonly zoomGestures = input(true);
  /** The stage lens to drive (default: the main StageToken). */
  readonly token = input<StageTokenProp>(StageToken);

  private readonly host = injectKernelHost();
  private readonly stage = injectOptionalCapabilityFor(() => this.token());
  private readonly ix = injectOptionalCapability(InteractionToken);
  private readonly useHub = computed(() => this.interaction() && this.ix() !== null);
  // The hub's resolved cursor (text/grab/…), applied to the viewport when driving.
  private readonly hubCursor = this.host.value(() => this.ix()?.cursor() ?? 'default');
  protected readonly cursor = computed(() => (this.useHub() ? this.hubCursor() : null));

  protected readonly documentId = injectDocumentId();
  // visiblePages already folds in the camera (each page carries its
  // device-snapped screenX/screenY + transform), so panning re-emits the list —
  // no separate camera subscription needed for positioning. The capability
  // memoizes, so Object.is equality suffices.
  protected readonly pages = injectOptionalSelectorFor(
    () => this.token(),
    (c) => c.visiblePages(),
    EMPTY_PAGES,
  );
  // Reserved chrome bands (screen px), uniform across pages — the frame the
  // outer box reserves and the chrome template paints into.
  protected readonly frame = injectOptionalSelectorFor(
    () => this.token(),
    (c) => c.pageFrame(),
    NO_FRAME,
    frameEqual,
  );

  private readonly pageTemplateDir = contentChild(EpdfPageTemplate);
  private readonly chromeTemplateDir = contentChild(EpdfPageChrome);
  protected readonly pageTemplate = computed(() => this.pageTemplateDir()?.template ?? null);
  protected readonly chromeTemplate = computed(() => this.chromeTemplateDir()?.template ?? null);

  constructor() {
    if (!isPlatformBrowser(inject(PLATFORM_ID))) return;
    const el = inject(ElementRef).nativeElement as HTMLElement;
    const zone = inject(NgZone);

    // Rebinds when the stage capability (document open/close/switch, token
    // change), hub, or gesture flags change — the Angular spelling of the React
    // Stage effect and its dependency array.
    effect((onCleanup) => {
      const stage = this.stage();
      const ix = this.ix();
      const useHub = this.interaction() && !!ix;
      const panFallback = this.panFallback();
      const zoomGestures = this.zoomGestures();
      if (!stage) return; // no document yet — nothing to drive

      const cleanups: Array<() => void> = [];
      zone.runOutsideAngular(() => {
        // The WHOLE browser binding — viewport/DPR reporting, sample
        // normalization, gesture controller — is the shared @embedpdf/web
        // surface, so every framework adapter has one feel. This component
        // keeps only Angular glue.
        cleanups.push(
          createStageSurface(el, stage, {
            hub: useHub ? ix : null,
            source: stage.lensId(),
            zoomGestures,
          }),
        );
        // Interaction opt-in lives WITH the sample source: the same knob that
        // forwards this lens's samples also registers its pan-scroll handler,
        // lens-scoped — two stages on one document can never pan each other.
        if (useHub && ix) {
          cleanups.push(
            ix.registerHandler(createScrollHandler(stage, ix, { panFallback }), {
              source: stage.lensId(),
            }),
          );
        }
      });
      onCleanup(() => cleanups.forEach((fn) => fn()));
    });
  }
}

// packages/framework/react/src/stage.tsx
/**
 * Stage / RenderLayer + facade hooks.
 *
 * <Stage> virtualizes and positions page surfaces by the camera, and hands each
 * one to YOUR render prop — you bring the layers. (The standalone, Stage-free
 * single-page surface lives in `./page-view` so it never pulls the stage plugin.)
 */

// One-line-per-feature: registration travels with the UI.
export * from '@embedpdf/plugin-stage';
import * as React from 'react';
import { useLayoutEffect, useMemo, useRef } from 'react';
import { StageToken, createScrollHandler, settingsEqual } from '@embedpdf/plugin-stage';
import type { StageCapability, VisiblePage } from '@embedpdf/plugin-stage';
import type { CapabilityToken } from '@embedpdf/core';

/** Which stage lens to bind to. Defaults to the main StageToken — pass a custom
 *  token to drive an additional lens (e.g. a wrapped thumbnail sidebar). */
export type StageTokenProp = CapabilityToken<StageCapability>;
import type { PageFrame } from '@embedpdf/core-geometry';
import { InteractionToken } from '@embedpdf/plugin-interaction/contract';
import { createStageSurface } from '@embedpdf/web';
import { ProjectorProvider, type ProjectorBinding, type ViewProjector } from './anchored';
import {
  makePageContext,
  PageProvider,
  useCapability,
  useDocumentId,
  useKernelValue,
  useOptionalCapability,
  useSelector,
} from './runtime';
import type { PageContextValue } from './runtime';

function PageSurface({
  documentId,
  page,
  frame,
  stage,
  render,
  chrome,
}: {
  documentId: string;
  page: VisiblePage;
  /** Reserved chrome bands around the page (screen px); the layout reserved the
   *  matching space, so the outer box tiles into it. */
  frame: PageFrame;
  /** The stage capability — the demand getter reads visibility LIVE off it. */
  stage: StageCapability;
  render: (page: PageContextValue) => React.ReactNode;
  chrome?: (page: PageContextValue) => React.ReactNode;
}) {
  const ref = useRef<HTMLDivElement>(null);
  const t = page.transform;
  const rotation = page.rotation;
  // All geometry comes from the transform: the DISPLAY footprint (viewWidth/Height,
  // already w↔h-swapped + device-snapped) and the UN-rotated content box
  // (contentWidth/Height). The shell never re-derives `* zoom` / `* dpr` / snapping.
  const outerW = t.viewWidth + frame.left + frame.right;
  const outerH = t.viewHeight + frame.top + frame.bottom;
  // page.screenX/screenY are the device-snapped footprint top-left; the outer box
  // sits one frame further out so the content keeps its scene position.
  const left = page.screenX - frame.left;
  const top = page.screenY - frame.top;
  // Center the (possibly rotated) content box on the display box and rotate about
  // its center — NO translate(), so rotation 0 carries no transform and pixel-snaps
  // like the axis-aligned shadow behind it (no hairline seam).
  const contentLeft = frame.left + (t.viewWidth - t.contentWidth) / 2;
  const contentTop = frame.top + (t.viewHeight - t.contentHeight) / 2;
  // The page-view DEMAND is a PULL: the getter closes over
  // stable references (capability + pon) and reads the stage's live state at
  // call time — visibility is the STAGE's data (`VisiblePage.visibleRect`),
  // not something an adapter re-derives or caches. Absent from the visible
  // set = zero rect ("want nothing"), distinct from PageView's undefined
  // getter ("whole page").
  const ctx = useMemo(
    () =>
      makePageContext(
        documentId,
        // the hosting lens — per-view raster planning keys tile state by it,
        // so a thumbnail rail and the main view never fight over one plan
        stage.lensId(),
        page.pon,
        page.pageIndex,
        frame,
        t,
        () => ref.current!.getBoundingClientRect(),
        () => {
          const live = stage.visiblePages().find((p) => p.pon === page.pon);
          return live
            ? { desiredDeviceWidth: live.transform.deviceWidth, visibleRect: live.visibleRect }
            : {
                desiredDeviceWidth: t.deviceWidth,
                visibleRect: { x: 0, y: 0, width: 0, height: 0 },
              };
        },
      ),
    [documentId, page.pon, page.pageIndex, frame, t, stage],
  );
  return (
    <div style={{ position: 'absolute', left, top, width: outerW, height: outerH }}>
      <PageProvider value={ctx}>
        {/* drop shadow ONLY — axis-aligned at the content box (inset by the frame),
            transparent fill so it can never peek out behind the bitmap, and it
            stays put under rotation. */}
        <div
          style={{
            position: 'absolute',
            left: frame.left,
            top: frame.top,
            width: t.viewWidth,
            height: t.viewHeight,
            // themeable: override via the CSS variable (app stylesheet), no props
            boxShadow: 'var(--epdf-page-shadow, 0 6px 18px rgba(0,0,0,.18))',
          }}
        />
        {/* the page: white backing + bitmap as ONE rasterized box, so there is no
            seam between them and nothing white larger than the bitmap to leak.
            The ONLY thing rotation turns; markers/annotations ride it in content
            coordinates. Rotation 0 carries no transform → pixel-snaps cleanly. */}
        <div
          ref={ref}
          style={{
            position: 'absolute',
            left: contentLeft,
            top: contentTop,
            width: t.contentWidth,
            height: t.contentHeight,
            background: '#fff',
            transform: rotation ? `rotate(${rotation}deg)` : undefined,
            // We render our own selection highlights — suppress native text/image
            // selection (and the double-click image grab) on the whole page subtree.
            userSelect: 'none',
            WebkitUserSelect: 'none',
          }}
        >
          {render(ctx)}
        </div>
        {/* box-space chrome — labels, selection border, per-page buttons — fills
            the outer box, NEVER rotates. Bands are plain regions: a label is
            `bottom:0; height: frame.bottom`, a button row `top:0; height: frame.top`. */}
        {chrome?.(ctx)}
      </PageProvider>
    </div>
  );
}

export interface StageProps {
  /**
   * PAGE-SPACE content for each visible page (RenderLayer, annotations,
   * markers). Rendered inside the page's content frame, so it ROTATES with the
   * page's display rotation — coordinates are plain PDF points.
   */
  children: (page: PageContextValue) => React.ReactNode;
  /**
   * BOX-SPACE chrome for each visible page (page-number label, selection
   * border, a per-page rotate/delete button). Rendered into the OUTER box
   * (content + reserved `pageFrame`), so it does NOT rotate and the reserved
   * bands are plain regions (`bottom:0; height: page.frame.bottom`). The three
   * coordinate spaces: `children` (page content), `pageChrome` (page box +
   * frame), `overlay` (viewport).
   */
  pageChrome?: (page: PageContextValue) => React.ReactNode;
  /** Viewport-space UI (menus, controls) rendered above the pages. */
  overlay?: React.ReactNode;
  /**
   * Route this Stage's pointer events to the interaction hub (page-resolved via
   * `pageAt`) — AND register this lens's tool-gated pan-scroll handler with it
   * (lens-scoped, so multiple stages on one document never pan each other).
   * Pan is then the `pan` tool's job and dragging in `pointer` mode selects
   * text (incl. across pages).
   *
   * Default TRUE: registering `interactionPlugin()` is the one opt-in — tools
   * just work; without the hub this is inert and the stage falls back to
   * built-in drag-to-pan, so a hub-less setup costs nothing. Set `false` on
   * SECONDARY lenses (a thumbnail rail) that should stay click-to-navigate
   * instead of feeding the document's tools.
   */
  interaction?: boolean;
  /**
   * With {@link interaction}: let drags over page GAPS pan regardless of the
   * active tool (and show a grab cursor there) — the gutter always pans; there
   * is nothing to draw/select outside a page. Default true.
   */
  panFallback?: boolean;
  /**
   * Ambient ZOOM gestures on this stage: ctrl/cmd+wheel and trackpad pinch
   * (Safari gesture events included). Default true. Turn OFF for follower
   * lenses with a fixed magnification — a thumbnail rail should scroll under
   * cmd+wheel, not zoom — so a zoom-wheel falls through to ordinary wheel
   * pan, and pinches are still swallowed (they never page-zoom the browser).
   */
  zoomGestures?: boolean;
  /** The stage lens to drive (default: the main StageToken). */
  token?: StageTokenProp;
  className?: string;
  style?: React.CSSProperties;
}

export function Stage({
  children,
  pageChrome,
  overlay,
  interaction = true,
  panFallback = true,
  zoomGestures = true,
  token = StageToken,
  className,
  style,
}: StageProps) {
  const stage = useCapability(token);
  const ix = useOptionalCapability(InteractionToken);
  const useHub = interaction && !!ix;
  // The hub's resolved cursor (text/grab/…), applied to the viewport when driving.
  const hubCursor = useKernelValue(() => ix?.cursor() ?? 'default');
  const ref = useRef<HTMLDivElement>(null);
  const docId = useDocumentId();
  // visiblePages already folds in the camera (each page carries its device-snapped
  // screenX/screenY + transform), so panning re-emits the list — no separate
  // camera subscription needed for positioning.
  const pages = useSelector(token, (c) => c.visiblePages()); // memoized -> stable ref
  // Reserved chrome bands (screen px), uniform across pages — the frame the
  // outer box reserves and `pageChrome` paints into.
  const frame = useSelector(
    token,
    (c) => c.pageFrame(),
    (a, b) => a.top === b.top && a.right === b.right && a.bottom === b.bottom && a.left === b.left,
  );

  // The Stage's ViewProjector: anchored UI (menus, popovers) positions through
  // the CAMERA — pure state, no DOM reads, no portal, and NO subscription:
  // `pages` (visiblePages) is the binding's revision, so a camera change
  // re-renders the pages AND every anchored consumer in the SAME React
  // commit — surface and overlay can never paint a frame apart.
  const projector = useMemo<ViewProjector>(
    () => ({
      space: 'overlay',
      toScreen: (pon, rect) => stage.pageRectToScreen(pon, rect),
      toScreenPoint: (pon, at) => {
        const r = stage.pageRectToScreen(pon, { x: at.x, y: at.y, width: 0, height: 0 });
        return r ? { x: r.x, y: r.y } : null;
      },
      viewEnv: (pon) => {
        const t = stage.pageRect(pon)?.transform;
        return t ? { scale: t.viewScale, rotation: t.rotation, zoom: t.zoom } : null;
      },
    }),
    [stage],
  );
  const projectorBinding = useMemo<ProjectorBinding>(
    () => ({ projector, revision: pages }),
    [projector, pages],
  );

  useLayoutEffect(() => {
    const el = ref.current!;
    // The WHOLE browser binding — viewport/DPR reporting, sample normalization,
    // gesture controller — is the shared @embedpdf/web surface, so every
    // framework adapter has one feel. This component keeps only React glue.
    const detachSurface = createStageSurface(el, stage, {
      hub: useHub ? ix : null,
      source: stage.lensId(),
      zoomGestures,
    });
    // Interaction opt-in lives WITH the sample source: the same knob that
    // forwards this lens's samples also registers its pan-scroll handler,
    // lens-scoped — two stages on one document can never pan each other.
    const offScroll =
      useHub && ix
        ? ix.registerHandler(createScrollHandler(stage, ix, { panFallback }), {
            source: stage.lensId(),
          })
        : null;

    return () => {
      offScroll?.();
      detachSurface();
    };
  }, [stage, ix, useHub, zoomGestures, panFallback]);

  return (
    <div
      ref={ref}
      className={className}
      style={{
        position: 'relative',
        overflow: 'hidden',
        touchAction: 'none',
        ...(useHub ? { cursor: hubCursor } : null),
        ...style,
      }}
    >
      {pages.map((p) => (
        <PageSurface
          key={p.pon} // durable page identity — survives move/delete (matches Angular's `track p.pon`)
          documentId={docId ?? ''}
          page={p}
          frame={frame}
          stage={stage}
          render={children}
          chrome={pageChrome}
        />
      ))}
      {/* Anchored UI mounts in the overlay: absolute coords here are the
          projector's overlay space (the stage container). */}
      <ProjectorProvider value={projectorBinding}>{overlay}</ProjectorProvider>
    </div>
  );
}

// ── Facade hooks — thin sugar over the capability + generic binding ───────────
export function useStage(token: StageTokenProp = StageToken) {
  return useCapability(token);
}
export function useZoom(token: StageTokenProp = StageToken) {
  const s = useCapability(token);
  const zoom = useSelector(token, (c) => c.zoomLevel());
  const mode = useSelector(token, (c) => c.zoomMode());
  return {
    zoom,
    /** Active zoom intent: 'automatic' | 'fit-page' | 'fit-width' | 'fit-all' | 'custom'. */
    mode,
    zoomIn: s.zoomIn,
    zoomOut: s.zoomOut,
    fitWidth: s.fitWidth,
    fitPage: s.fitPage,
    fitAll: s.fitAll,
    automatic: s.automatic,
    zoomTo: s.zoomTo,
  };
}
export function usePages(token: StageTokenProp = StageToken) {
  const s = useCapability(token);
  const currentPage = useSelector(token, (c) => c.currentPage());
  const pageCount = useSelector(token, (c) => c.pageCount());
  return {
    currentPage,
    pageCount,
    goToPage: s.goToPage,
    next: s.next,
    prev: s.prev,
    reveal: s.reveal,
  };
}
export function useLayout(token: StageTokenProp = StageToken) {
  const s = useCapability(token);
  const flow = useSelector(token, (c) => c.flow());
  const layout = useSelector(token, (c) => c.layout());
  const spread = useSelector(token, (c) => c.spread());
  const sizing = useSelector(token, (c) => c.sizing());
  const bounded = useSelector(token, (c) => c.bounded());
  return {
    flow,
    layout,
    spread,
    sizing,
    bounded,
    setFlow: s.setFlow,
    setLayout: s.setLayout,
    setSpread: s.setSpread,
    setSizing: s.setSizing,
    setBounded: s.setBounded,
  };
}

/** The document's page list (with PDF labels) + the current item's pages — the
 *  data for page thumbnails / worksheet-style page tabs. */
export function usePageList(token: StageTokenProp = StageToken) {
  const pages = useSelector(
    token,
    (c) => c.pages(),
    (a, b) =>
      a.length === b.length && a.every((p, i) => p.pon === b[i].pon && p.label === b[i].label),
  );
  const current = useSelector(
    token,
    (c) => c.currentItemPages(),
    (a, b) => a.length === b.length && a.every((x, i) => x === b[i]),
  );
  return { pages, currentItemPages: current };
}

/**
 * All Stage settings + the batch `update`. This is the seam for "presets are a
 * customer concern": keep your own `Partial<StageSettings>` objects and apply them
 * with `update(preset)` (one anchor-preserving change).
 */
export function useStageSettings(token: StageTokenProp = StageToken) {
  const s = useCapability(token);
  // settingsEqual derives from the plugin's settings registry — a new setting is
  // covered here automatically, without this package spelling out the shape.
  const settings = useSelector(token, (c) => c.settings(), settingsEqual);
  return { settings, update: s.update, reset: s.resetView };
}
