// packages/plugin-tiling/src/shared/components/tile-img.tsx
import { ignore, PdfErrorCode } from '@embedpdf/models';
import { Tile } from '@embedpdf/plugin-tiling';
import { useEffect, useMemo, useRef, useState } from '@framework';

import { useTilingCapability } from '../hooks/use-tiling';

interface TileImgProps {
  documentId: string;
  pageIndex: number;
  tile: Tile;
  dpr: number;
  scale: number;
}

function paintBitmap(canvas: HTMLCanvasElement, bitmap: ImageBitmap) {
  try {
    canvas.width = bitmap.width;
    canvas.height = bitmap.height;
    canvas.getContext('bitmaprenderer')!.transferFromImageBitmap(bitmap);
  } catch {
    // Bitmap was detached
  }
}

export function TileImg({ documentId, pageIndex, tile, dpr, scale }: TileImgProps) {
  const { provides: tilingCapability } = useTilingCapability();
  const scope = useMemo(
    () => tilingCapability?.forDocument(documentId),
    [tilingCapability, documentId],
  );

  const relativeScale = scale / tile.srcScale;

  const [hasContent, setHasContent] = useState(false);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);

  /* kick off render exactly once per tile */
  useEffect(() => {
    if (!scope) return;

    let currentBitmap: ImageBitmap | null = null;
    const task = scope.renderTile({ pageIndex, tile, dpr });
    task.wait((output) => {
      currentBitmap = output;
      const canvas = canvasRef.current;
      if (canvas) {
        paintBitmap(canvas, output);
        currentBitmap = null; // transferred to canvas
        setHasContent(true);
      }
    }, ignore);

    return () => {
      task.abort({
        code: PdfErrorCode.Cancelled,
        message: 'canceled render task',
      });
      if (currentBitmap) {
        currentBitmap.close();
        currentBitmap = null;
      }
      setHasContent(false);
    };
  }, [scope, pageIndex, tile.id]);

  const positionStyle = {
    position: 'absolute' as const,
    left: tile.screenRect.origin.x * relativeScale,
    top: tile.screenRect.origin.y * relativeScale,
    width: tile.screenRect.size.width * relativeScale,
    height: tile.screenRect.size.height * relativeScale,
  };

  return (
    <canvas ref={canvasRef} style={{ ...positionStyle, display: hasContent ? 'block' : 'none' }} />
  );
}

// packages/plugin-tiling/src/svelte/components/TileImg.svelte
<script lang="ts">
  import type { Tile } from '@embedpdf/plugin-tiling';
  import { useTilingCapability } from '../hooks';
  import { ignore, PdfErrorCode } from '@embedpdf/models';
  import { untrack, onDestroy } from 'svelte';

  interface TileImgProps {
    documentId: string;
    pageIndex: number;
    tile: Tile;
    dpr: number;
    scale: number;
  }

  let { documentId, pageIndex, tile, dpr, scale }: TileImgProps = $props();
  const tilingCapability = useTilingCapability();

  // Derived scoped capability for the specific document
  const scope = $derived(tilingCapability.provides?.forDocument(documentId) ?? null);

  let canvasEl: HTMLCanvasElement | undefined = $state(undefined);
  let hasContent = $state(false);
  let currentBitmap: ImageBitmap | null = null;

  // Capture these values once per tile change
  const tileId = $derived(tile.id);
  const tileSrcScale = $derived(tile.srcScale);
  const tileScreenRect = $derived(tile.screenRect);
  const relativeScale = $derived(scale / tileSrcScale);

  const createPlainTile = (t: Tile): Tile => ({
    ...t,
    pageRect: {
      origin: { x: t.pageRect.origin.x, y: t.pageRect.origin.y },
      size: { width: t.pageRect.size.width, height: t.pageRect.size.height },
    },
    screenRect: {
      origin: { x: t.screenRect.origin.x, y: t.screenRect.origin.y },
      size: { width: t.screenRect.size.width, height: t.screenRect.size.height },
    },
  });

  function paintBitmap(bitmap: ImageBitmap) {
    if (!canvasEl) return;
    try {
      canvasEl.width = bitmap.width;
      canvasEl.height = bitmap.height;
      canvasEl.getContext('bitmaprenderer')!.transferFromImageBitmap(bitmap);
      hasContent = true;
    } catch {
      // Bitmap was detached
    }
  }

  /* kick off render exactly once per tile */
  $effect(() => {
    // Track only tileId and pageIndex as dependencies
    const _tileId = tileId;
    const _pageIndex = pageIndex;

    // Check if we already have content for this tile
    if (currentBitmap) return;

    if (!scope) return;

    // Clone to avoid reactive proxies that Web Workers cannot clone
    const plainTile = untrack(() => createPlainTile(tile));
    const task = scope.renderTile({
      pageIndex: _pageIndex,
      tile: plainTile,
      dpr,
    });
    task.wait((bitmap) => {
      if (currentBitmap) {
        currentBitmap.close();
      }
      currentBitmap = bitmap;
      paintBitmap(bitmap);
      currentBitmap = null; // transferred to canvas, don't close
    }, ignore);

    return () => {
      task.abort({
        code: PdfErrorCode.Cancelled,
        message: 'canceled render task',
      });
      // Clean up bitmap when tile changes
      if (currentBitmap) {
        currentBitmap.close();
        currentBitmap = null;
        hasContent = false;
      }
    };
  });

  onDestroy(() => {
    if (currentBitmap) {
      currentBitmap.close();
      currentBitmap = null;
    }
  });
</script>

<canvas
  bind:this={canvasEl}
  style:position="absolute"
  style:left={`${tileScreenRect.origin.x * relativeScale}px`}
  style:top={`${tileScreenRect.origin.y * relativeScale}px`}
  style:width={`${tileScreenRect.size.width * relativeScale}px`}
  style:height={`${tileScreenRect.size.height * relativeScale}px`}
  style:display={hasContent ? 'block' : 'none'}
></canvas>
